# Generated by Django 3.2.6 on 2021-09-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='vody',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tittle',
        ),
    ]
